all: gen0 gen1 gen2 gen3 gen4

gen0: generator0.cc
	g++ -Wall -g generator0.cc -o gen0
gen1: generator1.cc
	g++ -Wall -g generator1.cc -o gen1
gen2: generator2.cc
	g++ -Wall -g generator2.cc -o gen2
gen3: generator3.cc
	g++ -Wall -g generator3.cc -o gen3
gen4: generator4.cc
	g++ -Wall -g generator4.cc -o gen4

clean:
	rm -f gen0.o
	rm -f gen0
	rm -f gen1.o
	rm -f gen1
	rm -f gen2.o
	rm -f gen2
	rm -f gen3.o
	rm -f gen3
	rm -f gen4.o
	rm -f gen4
